### ISSUE TITLE
Creating properties works but returns error nonetheless

### ISSUE THREAD

**Issue by dljcollette** [creativesoftwarefdn/weaviate#842] opened 2019-04-18 07:12 UTC
`POST http://localhost:8080/weaviate/v1/schema/things/Animals/properties/` with body `{ cardinality: "atMostOne", dataType: ["boolean"], description: "", keywords: [], name: "name" }` returns `[{message: "Name 'name' already in use as a property name for class 'Animals'"}]` with status code `422 Unprocessable Entity`.

The property `name` is actually created but I would expect the response to return no errors.

Please keep in mind that an `OPTIONS` call is being made by the browser prior to doing the post.

**Comment by etiennedi** [comment] 2019-04-18 07:13
@dljcollette The class Animals was previously created without any properties?

**Comment by dljcollette** [comment] 2019-04-18 07:14
Yes indeed

**Comment by dljcollette** [comment] 2019-04-18 07:28
The same happens when performing a `PUT`, which returns `no such prop with name 'name' found in class 'Animals' in the schema. Check your schema files for which properties in this class are available`

**Comment by etiennedi** [comment] 2019-04-18 07:31
@dljcollette 
> when performing a PUT

Could you list the whole path? From The error message I assume this would be a `PUT` on `/things/Animals`, but from the context it would make more sense if this was a put on `/schema/things/Animals/properties/name`?

**Comment by dljcollette** [comment] 2019-04-18 07:35
`PUT http://localhost:8080/weaviate/v1/schema/things/Animals/properties/name` returns `{ error: [ message: "no such prop with name 'name' found in class 'Animals' in the schema. Check your schema files for which properties in this class are available" ] }` with status code `422 Unprocessable Entity`

**Comment by etiennedi** [comment] 2019-04-18 07:46
Unfortunately with an empty db, I can't reproduce it, there it works fine: 
```
$ curl -H "Content-Type: application/json" -X POST http://localhost:8080/weaviate/v1/schema/things/Animal/properties/ -d '{ "cardinality": "atMostOne", "dataType": ["boolean"], "description": "", "keywords": [], "name": "name" }'
{"cardinality":"atMostOne","dataType":["boolean"],"name":"name"}
```

My assumption would be that it is somehow tied to the other classes in the schema. Do you also run into this error when you try the same steps on an empty weaviate?

**Comment by dljcollette** [comment] 2019-04-18 08:04
When I perform it in curl it also works for me. So the only difference I could notice between curl and the browser is the `OPTIONS` request being made by the browser.

**Comment by etiennedi** [comment] 2019-04-18 08:06
ok, I'll try to reproduce it from the playground instead to see if that changes anything :)

**Comment by etiennedi** [comment] 2019-04-18 08:29
I just tried it through the Playground but - with an otherwise empty db - it also worked fine. So my only other lead would be that it depends on the other classes in the schema.

Could you attach the output of `GET /weaviate/v1/schema` for the configuration in which the error occurs in this issue? Maybe I can reproduce it if I import the exact same classes you have. Thanks.

**Comment by dljcollette** [comment] 2019-04-18 09:21
I've used the generator for classes, things, actions and links for Weaviate:
```
{"actions":{"classes":[{"class":"Gururaja","description":"No description on this auto-generated thing","properties":[{"dataType":["boolean"],"description":"No property description, either ;-)","name":"budong"},{"dataType":["boolean"],"description":"No property description, either ;-)","name":"moinak"},{"dataType":["string"],"description":"No property description, either ;-)","name":"irdc"},{"dataType":["int"],"description":"No property description, either ;-)","name":"blankenheim"}]},{"class":"Pleter","description":"No description on this auto-generated thing","properties":[{"dataType":["boolean"],"description":"No property description, either ;-)","name":"tpoint"},{"dataType":["number"],"description":"No property description, either ;-)","name":"howry"},{"dataType":["date"],"description":"No property description, either ;-)","name":"ardussi"},{"dataType":["date"],"description":"No property description, either ;-)","name":"simpang"},{"dataType":["date"],"description":"No property description, either ;-)","name":"arlette"},{"dataType":["Jandelsbrunn"],"description":"A reference to the class 'Jandelsbrunn'.","name":"inJandelsbrunn"}]},{"class":"Degarde","description":"No description on this auto-generated thing","properties":[{"dataType":["date"],"description":"No property description, either ;-)","name":"stenderup"},{"dataType":["string"],"description":"No property description, either ;-)","name":"hinuber"},{"dataType":["string"],"description":"No property description, either ;-)","name":"tz"},{"dataType":["boolean"],"description":"No property description, either ;-)","name":"lawell"},{"dataType":["Ntai"],"description":"A reference to the class 'Ntai'.","name":"inNtai"},{"dataType":["Yashuko"],"description":"A reference to the class 'Yashuko'.","name":"inYashuko"}]},{"class":"Jandelsbrunn","description":"No description on this auto-generated thing","properties":[{"dataType":["number"],"description":"No property description, either ;-)","name":"daesang"},{"dataType":["string"],"description":"No property description, either ;-)","name":"patission"},{"dataType":["Pleter"],"description":"A reference to the class 'Pleter'.","name":"inPleter"}]},{"class":"Ntai","description":"No description on this auto-generated thing","properties":[{"dataType":["number"],"description":"No property description, either ;-)","name":"ghasa"},{"dataType":["Degarde"],"description":"A reference to the class 'Degarde'.","name":"inDegarde"}]},{"class":"Antimelatoma","description":"No description on this auto-generated thing","properties":[{"dataType":["int"],"description":"No property description, either ;-)","name":"ujung"},{"dataType":["number"],"description":"No property description, either ;-)","name":"varadaraj"},{"dataType":["number"],"description":"No property description, either ;-)","name":"aravantinos"},{"dataType":["boolean"],"description":"No property description, either ;-)","name":"kulipirai"},{"dataType":["int"],"description":"No property description, either ;-)","name":"chrostkowo"},{"dataType":["int"],"description":"No property description, either ;-)","name":"satyapramoda"},{"dataType":["string"],"description":"No property description, either ;-)","name":"abdurrachman"},{"dataType":["Ntai"],"description":"A reference to the class 'Ntai'.","name":"inNtai"},{"dataType":["Jandelsbrunn"],"description":"A reference to the class 'Jandelsbrunn'.","name":"inJandelsbrunn"}]},{"class":"Minkend","description":"No description on this auto-generated thing","properties":[{"dataType":["string"],"description":"No property description, either ;-)","name":"gbd"},{"dataType":["boolean"],"description":"No property description, either ;-)","name":"reddit"},{"dataType":["number"],"description":"No property description, either ;-)","name":"venkaji"},{"dataType":["boolean"],"description":"No property description, either ;-)","name":"heropanti"},{"dataType":["Gururaja"],"description":"A reference to the class 'Gururaja'.","name":"inGururaja"}]},{"class":"Yashuko","description":"No description on this auto-generated thing","properties":[{"dataType":["int"],"description":"No property description, either ;-)","name":"isni"},{"dataType":["string"],"description":"No property description, either ;-)","name":"mufon"},{"dataType":["boolean"],"description":"No property description, either ;-)","name":"italtel"},{"dataType":["date"],"description":"No property description, either ;-)","name":"bcpst"},{"dataType":["boolean"],"description":"No property description, either ;-)","name":"sheritt"},{"dataType":["int"],"description":"No property description, either ;-)","name":"talkartoons"},{"dataType":["int"],"description":"No property description, either ;-)","name":"chochol"},{"dataType":["Minkend"],"description":"A reference to the class 'Minkend'.","name":"inMinkend"},{"dataType":["Telecomunicacions"],"description":"A reference to the class 'Telecomunicacions'.","name":"inTelecomunicacions"},{"dataType":["Antimelatoma"],"description":"A reference to the class 'Antimelatoma'.","name":"inAntimelatoma"}]},{"class":"Telecomunicacions","description":"No description on this auto-generated thing","properties":[{"dataType":["number"],"description":"No property description, either ;-)","name":"lepidopterous"},{"dataType":["number"],"description":"No property description, either ;-)","name":"hiwing"},{"dataType":["number"],"description":"No property description, either ;-)","name":"butzer"},{"dataType":["Minkend"],"description":"A reference to the class 'Minkend'.","name":"inMinkend"},{"dataType":["Jandelsbrunn"],"description":"A reference to the class 'Jandelsbrunn'.","name":"inJandelsbrunn"}]}],"type":"action"},"things":{"classes":[{"class":"Marinos","description":"No description on this auto-generated thing","properties":[{"dataType":["boolean"],"description":"No property description, either ;-)","name":"bracy"},{"dataType":["date"],"description":"No property description, either ;-)","name":"einion"}]},{"class":"Feith","description":"No description on this auto-generated thing","properties":[{"dataType":["string"],"description":"No property description, either ;-)","name":"vendemmia"}]},{"class":"Eastmond","description":"No description on this auto-generated thing","properties":[{"dataType":["boolean"],"description":"No property description, either ;-)","name":"sahamiyeh"},{"dataType":["Barao"],"description":"A reference to the class 'Barao'.","name":"inBarao"},{"dataType":["Hidehira"],"description":"A reference to the class 'Hidehira'.","name":"inHidehira"}]},{"class":"Ispi","description":"No description on this auto-generated thing","properties":[{"dataType":["number"],"description":"No property description, either ;-)","name":"dellamorte"},{"dataType":["Eastmond"],"description":"A reference to the class 'Eastmond'.","name":"inEastmond"}]},{"class":"Farmans","description":"No description on this auto-generated thing","properties":[{"dataType":["date"],"description":"No property description, either ;-)","name":"morstein"},{"dataType":["int"],"description":"No property description, either ;-)","name":"scheibenschlagen"},{"dataType":["int"],"description":"No property description, either ;-)","name":"pccf"},{"dataType":["number"],"description":"No property description, either ;-)","name":"metcall"},{"dataType":["int"],"description":"No property description, either ;-)","name":"manunulat"},{"dataType":["number"],"description":"No property description, either ;-)","name":"watino"},{"dataType":["Feith"],"description":"A reference to the class 'Feith'.","name":"inFeith"},{"dataType":["Eastmond"],"description":"A reference to the class 'Eastmond'.","name":"inEastmond"},{"dataType":["Ansnes"],"description":"A reference to the class 'Ansnes'.","name":"inAnsnes"},{"dataType":["Hidehira"],"description":"A reference to the class 'Hidehira'.","name":"inHidehira"}]},{"class":"Dialium","description":"No description on this auto-generated thing","properties":[{"dataType":["string"],"description":"No property description, either ;-)","name":"peisistratean"},{"dataType":["number"],"description":"No property description, either ;-)","name":"verbow"},{"dataType":["string"],"description":"No property description, either ;-)","name":"colorizing"},{"dataType":["number"],"description":"No property description, either ;-)","name":"mondrian"},{"dataType":["string"],"description":"No property description, either ;-)","name":"kokatnur"},{"dataType":["Ansnes"],"description":"A reference to the class 'Ansnes'.","name":"inAnsnes"},{"dataType":["Hidehira"],"description":"A reference to the class 'Hidehira'.","name":"inHidehira"}]},{"class":"Ansnes","description":"No description on this auto-generated thing","properties":[{"dataType":["boolean"],"description":"No property description, either ;-)","name":"chumsai"},{"dataType":["boolean"],"description":"No property description, either ;-)","name":"garcelle"},{"dataType":["string"],"description":"No property description, either ;-)","name":"stenciled"},{"dataType":["string"],"description":"No property description, either ;-)","name":"thrinacia"},{"dataType":["int"],"description":"No property description, either ;-)","name":"karapatan"},{"dataType":["number"],"description":"No property description, either ;-)","name":"ogygia"},{"dataType":["Dialium"],"description":"A reference to the class 'Dialium'.","name":"inDialium"},{"dataType":["Barao"],"description":"A reference to the class 'Barao'.","name":"inBarao"},{"dataType":["Marinos"],"description":"A reference to the class 'Marinos'.","name":"inMarinos"}]},{"class":"Hidehira","description":"No description on this auto-generated thing","properties":[{"dataType":["int"],"description":"No property description, either ;-)","name":"bitsbox"},{"dataType":["int"],"description":"No property description, either ;-)","name":"limousine"},{"dataType":["int"],"description":"No property description, either ;-)","name":"wuzzlewood"},{"dataType":["boolean"],"description":"No property description, either ;-)","name":"loreta"}]},{"class":"Barao","description":"No description on this auto-generated thing","properties":[{"dataType":["Marinos"],"description":"A reference to the class 'Marinos'.","name":"inMarinos"},{"dataType":["date"],"description":"No property description, either ;-)","name":"tumsa"},{"dataType":["Ispi"],"description":"A reference to the class 'Ispi'.","name":"inIspi"},{"dataType":["date"],"description":"No property description, either ;-)","name":"conasauga"}]},{"class":"Peter","properties":null},{"class":"Companie","description":"This is a company description","keywords":[{"keyword":"shops","weight":1}],"properties":[{"cardinality":"atMostOne","dataType":["string"],"description":"This is a company name","name":"name"},{"cardinality":"atMostOne","dataType":["string"],"name":"shops"},{"cardinality":"atMostOne","dataType":["string"],"name":"what"}]},{"class":"Animals","description":"This is an animal description","keywords":[{"keyword":"shops","weight":1}],"properties":[{"cardinality":"atMostOne","dataType":["string"],"name":"name"},{"cardinality":"atMostOne","dataType":["boolean"],"name":"isMamal"},{"cardinality":"atMostOne","dataType":["string"],"name":"test"},{"cardinality":"atMostOne","dataType":["boolean"],"name":"legs"},{"cardinality":"atMostOne","dataType":["boolean"],"name":"noses"},{"cardinality":"atMostOne","dataType":["boolean"],"name":"dugs"},{"cardinality":"atMostOne","dataType":["boolean"],"name":"hair"}]},{"class":"Fruits","description":"This is a description for fruit","keywords":[{"keyword":"shops","weight":1}],"properties":[{"cardinality":"atMostOne","dataType":["string"],"name":"name"}]}],"type":"thing"}}
```

**Comment by dljcollette** [comment] 2019-04-18 09:21
Which version of Weaviate are you using?

**Comment by dljcollette** [comment] 2019-04-18 10:44
I've `--force-recreate`ed the Docker instance and the issue seems to be gone.

**Comment by etiennedi** [comment] 2019-04-18 12:07
I think the learning here is that, there is a chance that we can get into a situation where a property is only partially created. What caused that situation is almost impossible to identify, but based on the code I can at least see the reason: The partial split between modiying the schema in the actual db backend and in our own representation of the schema. 

While we cannot make these two changes atomic. What we could do is roll-back all changes if one of the changes is not successful. I'll create an issue to do so.

**Comment by etiennedi** [comment] 2019-04-19 06:12
Closing in favor of #846

**Closed by etiennedi** 2019-04-19 06:12 UTC
